#!/usr/bin/env python3
"""Run every assembly configuration through check_assembly.py + the linkage
kinematics, then write DOCUMENTATION/QC_REPORT.md from build/qc/*.json."""
import glob, json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = [
    ("dynamo_generator", ["ratio=8"]), ("dynamo_generator", ["ratio=1"]),
    ("dynamo_generator", ["ratio=2"]), ("dynamo_generator", ["ratio=4"]),
    ("dynamo_generator", ["ratio=8", "crank=45"]), ("dynamo_generator", ["ratio=8", "crank=90"]),
    ("dynamo_generator", ["ratio=8", "crank=180"]), ("dynamo_generator", ["ratio=8", "crank=270"]),
    ("dynamo_generator", ["ratio=4", "crank=120"]),
    ("solar_vehicle", ['version="A"']), ("solar_vehicle", ['version="B"']),
    ("solar_vehicle", ['version="C"']), ("solar_vehicle", ['version="D"']),
    ("solar_vehicle", ['version="B"', "wheel_rot=9"]),
    ("wind_turbine", ["blades=3", 'style="standard"', "pitch=20"]),
    ("wind_turbine", ["blades=4", 'style="torque"', "pitch=45", "rotor=30"]),
    ("wind_turbine", ["blades=2", 'style="speed"', "pitch=0", "rotor=90"]),
    ("wind_turbine", ["blades=3", 'style="torque"', "pitch=-45", "rotor=60"]),
    ("pulley_lab", []),
    ("linkage_fourbar", ["crank=0"]), ("linkage_fourbar", ["crank=90"]),
    ("linkage_fourbar", ["crank=180"]), ("linkage_fourbar", ["crank=270"]),
]


def main():
    only = sys.argv[1:]
    ok = True
    for asm, defs in RUNS:
        if only and asm not in only:
            continue
        cmd = ["python3", os.path.join(ROOT, "tools", "check_assembly.py"), os.path.join(ROOT, "ASSEMBLIES", asm + ".scad")]
        for d in defs:
            cmd += ["-D", d]
        r = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        print(r.stdout.strip() or r.stderr[-1500:], flush=True)
        ok &= r.returncode == 0
    r = subprocess.run(["python3", os.path.join(ROOT, "tools", "linkage_check.py")], capture_output=True, text=True)
    ok &= r.returncode == 0
    print("== linkage kinematics:", "PASS" if r.returncode == 0 else "FAIL")
    write_report()
    sys.exit(0 if ok else 1)


def write_report():
    L = ["# Quality-control report (generated)", "",
         "Generated by `tools/verify_all.py` (assemblies) and `tools/qc.py` (parts). Re-run after any change.", "",
         "## 1. Virtual assemblies", "",
         "Each item of an assembly is rendered to its own STL in world coordinates; every pair of items is intersected "
         "with exact mesh booleans (manifold3d). *Clashes* = solid overlap > 0.05 mm³. Press fits that are meant to "
         "overlap (motor shaft in a 1.9 mm bore) are declared and listed as *allowed*.", "",
         "| Assembly / configuration | Items | Clashes | Allowed press fits | Gear meshes verified | Result |",
         "|---|---|---|---|---|---|"]
    meshes = []
    for f in sorted(glob.glob(os.path.join(ROOT, "build", "qc", "*.json"))):
        name = os.path.basename(f)[:-5]
        if name in ("parts", "linkage_fourbar_kinematics"):
            continue
        d = json.load(open(f))
        clashes = [e for e in d["interference"] if not e["allowed"]]
        allowed = [e for e in d["interference"] if e["allowed"]]
        L.append("| %s | %d | %s | %s | %d | %s |" % (
            name.replace("_", " "), d["items"],
            "; ".join("%s × %s %.2f mm³" % (e["a"], e["b"], e["volume_mm3"]) for e in clashes) or "none",
            "; ".join("%s × %s %.2f mm³" % (e["a"], e["b"], e["volume_mm3"]) for e in allowed) or "—",
            len(d["gear_meshes"]), "**PASS**" if d["ok"] else "**FAIL**"))
        for g in d["gear_meshes"]:
            meshes.append((name, g))
    L += ["", "## 2. Gear meshes", "",
          "Both gears are sliced at their mid-plane and rotated together through one full tooth pitch (48 steps) at the "
          "correct ratio. Pass = no tooth overlap at any step, flank gap < 0.35 mm at every step (the teeth really "
          "engage), and the pair locks when the 0.30 mm design backlash is taken up.", "",
          "| Configuration | Pair | Ratio | Centre distance (mm) | Max overlap (mm²) | Flank gap min–max (mm) | Locks w/o backlash | Result |",
          "|---|---|---|---|---|---|---|---|"]
    for name, g in meshes:
        L.append("| %s | %s | %s | %s | %s | %s–%s | %s | %s |" % (
            name.replace("_", " "), g["pair"], g["ratio"], g["centre_distance"], g["overlap_mm2"],
            g["flank_gap_min"], g["flank_gap_max"], g["locks_without_backlash"], "PASS" if g["ok"] else "FAIL"))
    k = os.path.join(ROOT, "build", "qc", "linkage_fourbar_kinematics.json")
    if os.path.exists(k):
        d = json.load(open(k))
        L += ["", "## 3. Four-bar linkage kinematics (360° sweep, 1° steps)", "",
              "| Check | Value |", "|---|---|"]
        for key, v in d.items():
            L.append("| %s | %s |" % (key.replace("_", " "), v))
    p = os.path.join(ROOT, "build", "qc", "parts.json")
    if os.path.exists(p):
        d = json.load(open(p))
        L += ["", "## 4. Parts", "",
              "%d parts checked by `tools/qc.py`: %d pass (watertight, consistent winding, manifold3d-valid, expected "
              "body count, on the bed, fits 200 mm). Details and printability measurements: [PARTS.md](PARTS.md)."
              % (len(d), sum(1 for r in d if not r["fails"]))]
        bad = [r for r in d if r["fails"]]
        for r in bad:
            L.append("* **%s**: %s" % (r["id"], "; ".join(r["fails"])))
    L.append("")
    open(os.path.join(ROOT, "DOCUMENTATION", "QC_REPORT.md"), "w").write("\n".join(L))


if __name__ == "__main__":
    main()
