"""Involute spur-gear template.

Geometry (CAD frame, Z-up, mm): an external spur gear with standard full-depth
involute teeth (addendum = module, dedendum = 1.25·module), extruded by the
face width T along +Z, with a concentric bore of diameter B.

The tooth outline is generated by the kernel from the `GearProfile` at compile
time, so the tooth count Z is a genuine live parameter. Key radii:
    pitch    r  = M·Z/2
    outer    ra = r + M           (bbox = 2·ra)
    root     rf = r − 1.25·M
There is no simple closed-form volume; the golden test bounds the compiled
volume between the root and addendum cylinders (less the bore).
"""

from __future__ import annotations

from ..domain.feature_program import (
    ExtrudeFeature,
    FeatureProgram,
    GearProfile,
    HoleFeature,
    Parameter,
    SketchFeature,
)
from . import PartTemplate, TemplateCheck

PARAMETERS: list[Parameter] = [
    Parameter(id="M", label="Module", value=2, min=0.5, max=10, step=0.5, unit="mm"),
    Parameter(id="Z", label="Teeth", value=20, min=6, max=120, step=1, integer=True, unit=""),
    Parameter(id="T", label="Face width", value=6, min=1, max=60, step=0.5),
    Parameter(id="B", label="Bore diameter", value=6, min=1, max=200, step=0.5),
    Parameter(
        id="PA", label="Pressure angle", value=20, min=14.5, max=30, step=0.5, unit="°"
    ),
]

CHECKS: list[TemplateCheck] = [
    TemplateCheck(
        expr="17 - Z",
        message=(
            "Fewer than 17 teeth undercuts at a 20° pressure angle — the tooth "
            "root is weakened; consider more teeth or a higher pressure angle"
        ),
    ),
    TemplateCheck(
        # bore leaves under 2 mm of rim to the tooth root (root dia = M·Z − 2.5·M)
        expr="B - (M*Z - 2.5*M) + 4",
        message="Bore is close to the tooth roots — thin rim, teeth may print weak",
    ),
]


def build(values: dict[str, float]) -> FeatureProgram:
    """Pure parameters→program mapping. `values` may override defaults."""
    parameters = [
        p.model_copy(update={"value": float(values.get(p.id, p.value))}) for p in PARAMETERS
    ]
    return FeatureProgram(
        name="Spur Gear",
        parameters=parameters,
        features=[
            SketchFeature(
                id="tooth_profile",
                plane="XY",
                profile=GearProfile(module="M", teeth="Z", pressure_angle="PA"),
            ),
            ExtrudeFeature(id="blank", of="tooth_profile", distance="T"),
            HoleFeature(id="bore", axis="Z", u=0, v=0, diameter="B"),
        ],
        provenance={"generator": "template:gear", "version": "1"},
    )


GEAR_TEMPLATE = PartTemplate(
    id="gear",
    name="Spur Gear",
    description=(
        "Parametric involute spur gear (standard full-depth teeth) with a "
        "concentric bore. Set module, tooth count, face width, bore, and "
        "pressure angle; the involute tooth profile is generated by the kernel."
    ),
    parameters=PARAMETERS,
    build=build,
    checks=CHECKS,
)
