// CRW-004 Cow Phone Stand - Resting Cowa
// Generated by scripts/generate.py - DO NOT EDIT (edit cad/products/*.py instead).
// Each import() is one toolhead region; colours follow the default tool assignment.
// Set SHOW_TOOL = 1..4 to isolate a single toolhead, 0 = all.
SHOW_TOOL = 0;

// T1 PLA Cow White: core body, eye highlight, eye ring, horn, head, body
if (SHOW_TOOL == 0 || SHOW_TOOL == 1) color([0.957, 0.945, 0.910]) import("CRW-004-cow-phone-stand__tool_1.stl", convexity = 10);
// T2 PLA Cow Black: eye, nostril, eye patch, hoof, tail tuft, tail, shoulder patch, rump patch, COWARAMUP band
if (SHOW_TOOL == 0 || SHOW_TOOL == 2) color([0.118, 0.118, 0.118]) import("CRW-004-cow-phone-stand__tool_2.stl", convexity = 10);
// T3 PLA Cow Pink: muzzle, inner ear
if (SHOW_TOOL == 0 || SHOW_TOOL == 3) color([0.949, 0.655, 0.710]) import("CRW-004-cow-phone-stand__tool_3.stl", convexity = 10);
// T4 TPU Cow Black: TPU pad (rear wall)
if (SHOW_TOOL == 0 || SHOW_TOOL == 4) color([0.118, 0.118, 0.118]) import("CRW-004-cow-phone-stand__tpu_pad_rear_wall.stl", convexity = 10);
// T4 TPU Cow Black: TPU pad (front lip)
if (SHOW_TOOL == 0 || SHOW_TOOL == 4) color([0.118, 0.118, 0.118]) import("CRW-004-cow-phone-stand__tpu_pad_front_lip.stl", convexity = 10);
// T4 TPU Cow Black: TPU pad (foot rear)
if (SHOW_TOOL == 0 || SHOW_TOOL == 4) color([0.118, 0.118, 0.118]) import("CRW-004-cow-phone-stand__tpu_pad_foot_rear.stl", convexity = 10);
// T4 TPU Cow Black: TPU pad (foot front)
if (SHOW_TOOL == 0 || SHOW_TOOL == 4) color([0.118, 0.118, 0.118]) import("CRW-004-cow-phone-stand__tpu_pad_foot_front.stl", convexity = 10);
