// CRW-003 Mini Collectible Cow - Resting Cowa
// Generated by scripts/generate.py - DO NOT EDIT (edit cad/products/*.py instead).
// Each import() is one toolhead region; colours follow the default tool assignment.
// Set SHOW_TOOL = 1..4 to isolate a single toolhead, 0 = all.
SHOW_TOOL = 0;

// T1 PLA Cow White: eye ring, body, legs, head, ears, tail + tuft
if (SHOW_TOOL == 0 || SHOW_TOOL == 1) color([0.957, 0.945, 0.910]) import("CRW-003-mini-cow-classic__tool_1.stl", convexity = 10);
// T2 PLA Cow Black: eyes, patches
if (SHOW_TOOL == 0 || SHOW_TOOL == 2) color([0.118, 0.118, 0.118]) import("CRW-003-mini-cow-classic__tool_2.stl", convexity = 10);
// T3 PLA Cow Pink: muzzle
if (SHOW_TOOL == 0 || SHOW_TOOL == 3) color([0.949, 0.655, 0.710]) import("CRW-003-mini-cow-classic__tool_3.stl", convexity = 10);
// T4 PLA Earth Brown: plinth, horns, hooves
if (SHOW_TOOL == 0 || SHOW_TOOL == 4) color([0.361, 0.251, 0.188]) import("CRW-003-mini-cow-classic__tool_4.stl", convexity = 10);
