// =====================================================================
//  gear_lib.scad — involute spur gears generated by a virtual rack
//  cutter (exactly how a real gear-hobbing machine makes them), so
//  small pinions get correct undercut automatically and every gear in
//  the set meshes with every other gear.
// =====================================================================
include <../../PARAMETERS/config.scad>
use <../stem_core.scad>

function pitch_r(z, m = gear_module)   = z * m / 2;
function tip_r(z, m = gear_module)     = pitch_r(z, m) + m;
function root_r(z, m = gear_module)    = pitch_r(z, m) - (1 + gear_clearance_k) * m;
function centre_distance(z1, z2, m = gear_module) = (z1 + z2) * m / 2;

// One rack-cutter tooth (cuts one tooth *space*). Pitch line on y = 0,
// tooth points toward -y (toward gear centre, which is at -rp).
module _cutter_tooth(m, pa, bl) {
    s  = PI * m / 2 + bl / 2;             // cutter tooth width at pitch line (thins gear tooth)
    hd = (1 + gear_clearance_k) * m;      // depth below pitch line (gear dedendum)
    ha = m + 0.5;                         // height above pitch line (beyond gear tip)
    t  = tan(pa);
    polygon([
        [-s / 2 + hd * t, -hd], [ s / 2 - hd * t, -hd],
        [ s / 2 + ha * t,  ha], [-s / 2 - ha * t,  ha]
    ]);
}

// Space swept by the rolling cutter for the tooth space centred on +Y.
module _tooth_space(z, m, pa, bl) {
    rp = pitch_r(z, m);
    ra = tip_r(z, m);
    rf = root_r(z, m);
    span = 2.2 * sqrt(ra * ra - rf * rf) / rp;      // radians of roll needed
    steps = 48;
    union() for (i = [0 : steps]) {
        th = -span + 2 * span * i / steps;          // gear rotation (rad)
        rotate(-th * 180 / PI) translate([-rp * th, rp]) _cutter_tooth(m, pa, bl);
    }
}

// 2D gear outline.
module gear2d(z, m = gear_module, pa = gear_pressure_angle, bl = gear_backlash) {
    difference() {
        circle(r = tip_r(z, m), $fn = max(4 * z, 60));
        for (k = [0 : z - 1]) rotate(k * 360 / z) _tooth_space(z, m, pa, bl);
    }
}

// 3D spur gear with 0.5 mm tooth chamfers top & bottom (safe edges,
// elephant-foot relief). Sits on z = 0.
module gear_body(z, w = gear_width, m = gear_module) {
    ra = tip_r(z, m);
    c = 0.5;
    intersection() {
        linear_extrude(w) gear2d(z, m);
        rotate_extrude($fn = max(4 * z, 60)) polygon([[0, 0], [ra - c, 0], [ra + 0.01, c], [ra + 0.01, w - c], [ra - c, w], [0, w]]);
    }
}
