// CRW-001 Cowaramup Cow Keyring
// Generated by scripts/generate.py - DO NOT EDIT (edit cad/products/*.py instead).
// Each import() is one toolhead region; colours follow the default tool assignment.
// Set SHOW_TOOL = 1..4 to isolate a single toolhead, 0 = all.
SHOW_TOOL = 0;

// T1 PLA Cow White: core body, eye highlights, eye ring, head, ears, keyring loop
if (SHOW_TOOL == 0 || SHOW_TOOL == 1) color([0.957, 0.945, 0.910]) import("CRW-001-cowaramup-keyring-classic-small__tool_1.stl", convexity = 10);
// T2 PLA Cow Black: eyes, nostrils, forehead spot, signature patch
if (SHOW_TOOL == 0 || SHOW_TOOL == 2) color([0.118, 0.118, 0.118]) import("CRW-001-cowaramup-keyring-classic-small__tool_2.stl", convexity = 10);
// T3 PLA Cow Pink: muzzle, inner ears
if (SHOW_TOOL == 0 || SHOW_TOOL == 3) color([0.949, 0.655, 0.710]) import("CRW-001-cowaramup-keyring-classic-small__tool_3.stl", convexity = 10);
// T4 TPU Earth Brown: horns
if (SHOW_TOOL == 0 || SHOW_TOOL == 4) color([0.361, 0.251, 0.188]) import("CRW-001-cowaramup-keyring-classic-small__tool_4.stl", convexity = 10);
